name: Generate Snake

on:
  # Chạy tự động mỗi 12 giờ đêm
  schedule:
    - cron: "0 0 * * *" 
  # Cho phép chạy thủ công để test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # Tên user của bạn
          github_user_name: DuyHieu2004
          # Các file ảnh con rắn sẽ được tạo ra
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to Output Branch
        uses: crazy-max/gh-action-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
